call makemoviepart part-02
call makemoviepart part-03
call makemoviepart part-04
call makemoviepart part-05
call makemoviepart part-06
call makemoviepart part-07
call makemoviepart part-08
call makemoviepart part-09
call makemoviepart part-10
call makemoviepart part-11
call makemoviepart part-12
call makemoviepart part-13
call makemoviepart part-14
call makemoviepart part-15
call makemoviepart part-16
call makemoviepart part-17
call makemoviepart part-18
call makemoviepart part-19
call makemoviepart part-20
call makemoviepart part-21
call makemoviepart part-22
call makemoviepart part-23
call makemoviepart part-24
call makemoviepart part-25
call makemoviepart part-26
ffmpeg -f concat -i movieparts.txt -c copy all.mp4
